[package]
name = "waypoint_based_2d_destructible_terrain"
version = "0.14.1"
authors = ["Armin Schäfer"]
readme = "README.md"
edition = "2021"
keywords = ["Indie"]

[dependencies]
#bevy = "0.14.2"
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "636e99c9fb384fc28ae522fac10ab8811f14c9ff" } # Online for debug.

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
